### ISSUE TITLE
5th order Legendre polynomial

### ISSUE THREAD

**Issue by NatsukiHosono** [mikinakajima/MeltScalingLaw#3]
In line 128, melt_model.py it is given by 
return 1.0 / 8.0 * (63 * x ** 5.0 - 70 * x ** 3.0 - 15 * x)
but should be (iirc)
return 1.0 / 8.0 * (63 * x ** 5.0 - 70 * x ** 3.0 + 15 * x)

**Comment by mikinakajima** [comment]
Thank you, this is now resolved.
